FROM rust AS base
COPY --from=node:20-slim /usr/local/bin /usr/local/bin
COPY --from=node:20-slim /usr/local/lib/node_modules /usr/local/lib/node_modules
RUN corepack enable pnpm
RUN npm install -g bun
RUN apt update && apt install -y libssl-dev libgtk-3-dev libwebkit2gtk-4.1-dev
WORKDIR /app
COPY ./Backboard .
RUN pnpm install

FROM base AS build
ENTRYPOINT ["pnpm", "tauri", "build"]
CMD ["-b", "deb"]
